/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log.proto

// Protobuf Java Version: 3.25.8
package com.alipay.sofa.jraft.entity.codec.v2;

public final class LogOutter {
    private LogOutter() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface PBLogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.PBLogEntry)
                                        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .jraft.EntryType type = 1;</code>
         * @return Whether the type field is set.
         */
        boolean hasType();

        /**
         * <code>required .jraft.EntryType type = 1;</code>
         * @return The type.
         */
        com.alipay.sofa.jraft.entity.EnumOutter.EntryType getType();

        /**
         * <code>required int64 term = 2;</code>
         * @return Whether the term field is set.
         */
        boolean hasTerm();

        /**
         * <code>required int64 term = 2;</code>
         * @return The term.
         */
        long getTerm();

        /**
         * <code>required int64 index = 3;</code>
         * @return Whether the index field is set.
         */
        boolean hasIndex();

        /**
         * <code>required int64 index = 3;</code>
         * @return The index.
         */
        long getIndex();

        /**
         * <code>repeated bytes peers = 4;</code>
         * @return A list containing the peers.
         */
        java.util.List<com.google.protobuf.ByteString> getPeersList();

        /**
         * <code>repeated bytes peers = 4;</code>
         * @return The count of peers.
         */
        int getPeersCount();

        /**
         * <code>repeated bytes peers = 4;</code>
         * @param index The index of the element to return.
         * @return The peers at the given index.
         */
        com.google.protobuf.ByteString getPeers(int index);

        /**
         * <code>repeated bytes old_peers = 5;</code>
         * @return A list containing the oldPeers.
         */
        java.util.List<com.google.protobuf.ByteString> getOldPeersList();

        /**
         * <code>repeated bytes old_peers = 5;</code>
         * @return The count of oldPeers.
         */
        int getOldPeersCount();

        /**
         * <code>repeated bytes old_peers = 5;</code>
         * @param index The index of the element to return.
         * @return The oldPeers at the given index.
         */
        com.google.protobuf.ByteString getOldPeers(int index);

        /**
         * <code>required bytes data = 6;</code>
         * @return Whether the data field is set.
         */
        boolean hasData();

        /**
         * <code>required bytes data = 6;</code>
         * @return The data.
         */
        com.google.protobuf.ByteString getData();

        /**
         * <code>optional int64 checksum = 7;</code>
         * @return Whether the checksum field is set.
         */
        boolean hasChecksum();

        /**
         * <code>optional int64 checksum = 7;</code>
         * @return The checksum.
         */
        long getChecksum();

        /**
         * <code>repeated bytes learners = 8;</code>
         * @return A list containing the learners.
         */
        java.util.List<com.google.protobuf.ByteString> getLearnersList();

        /**
         * <code>repeated bytes learners = 8;</code>
         * @return The count of learners.
         */
        int getLearnersCount();

        /**
         * <code>repeated bytes learners = 8;</code>
         * @param index The index of the element to return.
         * @return The learners at the given index.
         */
        com.google.protobuf.ByteString getLearners(int index);

        /**
         * <code>repeated bytes old_learners = 9;</code>
         * @return A list containing the oldLearners.
         */
        java.util.List<com.google.protobuf.ByteString> getOldLearnersList();

        /**
         * <code>repeated bytes old_learners = 9;</code>
         * @return The count of oldLearners.
         */
        int getOldLearnersCount();

        /**
         * <code>repeated bytes old_learners = 9;</code>
         * @param index The index of the element to return.
         * @return The oldLearners at the given index.
         */
        com.google.protobuf.ByteString getOldLearners(int index);
    }

    /**
     * Protobuf type {@code jraft.PBLogEntry}
     */
    public static final class PBLogEntry extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:jraft.PBLogEntry)
                                                                                       PBLogEntryOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use PBLogEntry.newBuilder() to construct.
        private PBLogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PBLogEntry() {
            type_ = 0;
            peers_ = emptyList(com.google.protobuf.ByteString.class);
            oldPeers_ = emptyList(com.google.protobuf.ByteString.class);
            data_ = com.google.protobuf.ByteString.EMPTY;
            learners_ = emptyList(com.google.protobuf.ByteString.class);
            oldLearners_ = emptyList(com.google.protobuf.ByteString.class);
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new PBLogEntry();
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.class,
                    com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.Builder.class);
        }

        private int             bitField0_;
        public static final int TYPE_FIELD_NUMBER = 1;
        private int             type_             = 0;

        /**
         * <code>required .jraft.EntryType type = 1;</code>
         * @return Whether the type field is set.
         */
        @java.lang.Override
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required .jraft.EntryType type = 1;</code>
         * @return The type.
         */
        @java.lang.Override
        public com.alipay.sofa.jraft.entity.EnumOutter.EntryType getType() {
            com.alipay.sofa.jraft.entity.EnumOutter.EntryType result = com.alipay.sofa.jraft.entity.EnumOutter.EntryType
                .forNumber(type_);
            return result == null ? com.alipay.sofa.jraft.entity.EnumOutter.EntryType.ENTRY_TYPE_UNKNOWN : result;
        }

        public static final int TERM_FIELD_NUMBER = 2;
        private long            term_             = 0L;

        /**
         * <code>required int64 term = 2;</code>
         * @return Whether the term field is set.
         */
        @java.lang.Override
        public boolean hasTerm() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required int64 term = 2;</code>
         * @return The term.
         */
        @java.lang.Override
        public long getTerm() {
            return term_;
        }

        public static final int INDEX_FIELD_NUMBER = 3;
        private long            index_             = 0L;

        /**
         * <code>required int64 index = 3;</code>
         * @return Whether the index field is set.
         */
        @java.lang.Override
        public boolean hasIndex() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>required int64 index = 3;</code>
         * @return The index.
         */
        @java.lang.Override
        public long getIndex() {
            return index_;
        }

        public static final int                                                           PEERS_FIELD_NUMBER = 4;
        @SuppressWarnings("serial")
        private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> peers_             = emptyList(com.google.protobuf.ByteString.class);

        /**
         * <code>repeated bytes peers = 4;</code>
         * @return A list containing the peers.
         */
        @java.lang.Override
        public java.util.List<com.google.protobuf.ByteString> getPeersList() {
            return peers_;
        }

        /**
         * <code>repeated bytes peers = 4;</code>
         * @return The count of peers.
         */
        public int getPeersCount() {
            return peers_.size();
        }

        /**
         * <code>repeated bytes peers = 4;</code>
         * @param index The index of the element to return.
         * @return The peers at the given index.
         */
        public com.google.protobuf.ByteString getPeers(int index) {
            return peers_.get(index);
        }

        public static final int                                                           OLD_PEERS_FIELD_NUMBER = 5;
        @SuppressWarnings("serial")
        private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> oldPeers_              = emptyList(com.google.protobuf.ByteString.class);

        /**
         * <code>repeated bytes old_peers = 5;</code>
         * @return A list containing the oldPeers.
         */
        @java.lang.Override
        public java.util.List<com.google.protobuf.ByteString> getOldPeersList() {
            return oldPeers_;
        }

        /**
         * <code>repeated bytes old_peers = 5;</code>
         * @return The count of oldPeers.
         */
        public int getOldPeersCount() {
            return oldPeers_.size();
        }

        /**
         * <code>repeated bytes old_peers = 5;</code>
         * @param index The index of the element to return.
         * @return The oldPeers at the given index.
         */
        public com.google.protobuf.ByteString getOldPeers(int index) {
            return oldPeers_.get(index);
        }

        public static final int                DATA_FIELD_NUMBER = 6;
        private com.google.protobuf.ByteString data_             = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>required bytes data = 6;</code>
         * @return Whether the data field is set.
         */
        @java.lang.Override
        public boolean hasData() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>required bytes data = 6;</code>
         * @return The data.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        public static final int CHECKSUM_FIELD_NUMBER = 7;
        private long            checksum_             = 0L;

        /**
         * <code>optional int64 checksum = 7;</code>
         * @return Whether the checksum field is set.
         */
        @java.lang.Override
        public boolean hasChecksum() {
            return ((bitField0_ & 0x00000010) != 0);
        }

        /**
         * <code>optional int64 checksum = 7;</code>
         * @return The checksum.
         */
        @java.lang.Override
        public long getChecksum() {
            return checksum_;
        }

        public static final int                                                           LEARNERS_FIELD_NUMBER = 8;
        @SuppressWarnings("serial")
        private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> learners_             = emptyList(com.google.protobuf.ByteString.class);

        /**
         * <code>repeated bytes learners = 8;</code>
         * @return A list containing the learners.
         */
        @java.lang.Override
        public java.util.List<com.google.protobuf.ByteString> getLearnersList() {
            return learners_;
        }

        /**
         * <code>repeated bytes learners = 8;</code>
         * @return The count of learners.
         */
        public int getLearnersCount() {
            return learners_.size();
        }

        /**
         * <code>repeated bytes learners = 8;</code>
         * @param index The index of the element to return.
         * @return The learners at the given index.
         */
        public com.google.protobuf.ByteString getLearners(int index) {
            return learners_.get(index);
        }

        public static final int                                                           OLD_LEARNERS_FIELD_NUMBER = 9;
        @SuppressWarnings("serial")
        private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> oldLearners_              = emptyList(com.google.protobuf.ByteString.class);

        /**
         * <code>repeated bytes old_learners = 9;</code>
         * @return A list containing the oldLearners.
         */
        @java.lang.Override
        public java.util.List<com.google.protobuf.ByteString> getOldLearnersList() {
            return oldLearners_;
        }

        /**
         * <code>repeated bytes old_learners = 9;</code>
         * @return The count of oldLearners.
         */
        public int getOldLearnersCount() {
            return oldLearners_.size();
        }

        /**
         * <code>repeated bytes old_learners = 9;</code>
         * @param index The index of the element to return.
         * @return The oldLearners at the given index.
         */
        public com.google.protobuf.ByteString getOldLearners(int index) {
            return oldLearners_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTerm()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasIndex()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasData()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeEnum(1, type_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeInt64(2, term_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeInt64(3, index_);
            }
            for (int i = 0; i < peers_.size(); i++) {
                output.writeBytes(4, peers_.get(i));
            }
            for (int i = 0; i < oldPeers_.size(); i++) {
                output.writeBytes(5, oldPeers_.get(i));
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                output.writeBytes(6, data_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                output.writeInt64(7, checksum_);
            }
            for (int i = 0; i < learners_.size(); i++) {
                output.writeBytes(8, learners_.get(i));
            }
            for (int i = 0; i < oldLearners_.size(); i++) {
                output.writeBytes(9, oldLearners_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeEnumSize(1, type_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, term_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, index_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < peers_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(peers_.get(i));
                }
                size += dataSize;
                size += 1 * getPeersList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < oldPeers_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(oldPeers_.get(i));
                }
                size += dataSize;
                size += 1 * getOldPeersList().size();
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(6, data_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(7, checksum_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < learners_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(learners_.get(i));
                }
                size += dataSize;
                size += 1 * getLearnersList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < oldLearners_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(oldLearners_.get(i));
                }
                size += dataSize;
                size += 1 * getOldLearnersList().size();
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry)) {
                return super.equals(obj);
            }
            com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry other = (com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry) obj;

            if (hasType() != other.hasType())
                return false;
            if (hasType()) {
                if (type_ != other.type_)
                    return false;
            }
            if (hasTerm() != other.hasTerm())
                return false;
            if (hasTerm()) {
                if (getTerm() != other.getTerm())
                    return false;
            }
            if (hasIndex() != other.hasIndex())
                return false;
            if (hasIndex()) {
                if (getIndex() != other.getIndex())
                    return false;
            }
            if (!getPeersList().equals(other.getPeersList()))
                return false;
            if (!getOldPeersList().equals(other.getOldPeersList()))
                return false;
            if (hasData() != other.hasData())
                return false;
            if (hasData()) {
                if (!getData().equals(other.getData()))
                    return false;
            }
            if (hasChecksum() != other.hasChecksum())
                return false;
            if (hasChecksum()) {
                if (getChecksum() != other.getChecksum())
                    return false;
            }
            if (!getLearnersList().equals(other.getLearnersList()))
                return false;
            if (!getOldLearnersList().equals(other.getOldLearnersList()))
                return false;
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasType()) {
                hash = (37 * hash) + TYPE_FIELD_NUMBER;
                hash = (53 * hash) + type_;
            }
            if (hasTerm()) {
                hash = (37 * hash) + TERM_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTerm());
            }
            if (hasIndex()) {
                hash = (37 * hash) + INDEX_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getIndex());
            }
            if (getPeersCount() > 0) {
                hash = (37 * hash) + PEERS_FIELD_NUMBER;
                hash = (53 * hash) + getPeersList().hashCode();
            }
            if (getOldPeersCount() > 0) {
                hash = (37 * hash) + OLD_PEERS_FIELD_NUMBER;
                hash = (53 * hash) + getOldPeersList().hashCode();
            }
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            if (hasChecksum()) {
                hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getChecksum());
            }
            if (getLearnersCount() > 0) {
                hash = (37 * hash) + LEARNERS_FIELD_NUMBER;
                hash = (53 * hash) + getLearnersList().hashCode();
            }
            if (getOldLearnersCount() > 0) {
                hash = (37 * hash) + OLD_LEARNERS_FIELD_NUMBER;
                hash = (53 * hash) + getOldLearnersList().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(java.nio.ByteBuffer data)
                                                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(java.nio.ByteBuffer data,
                                                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(com.google.protobuf.ByteString data)
                                                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(com.google.protobuf.ByteString data,
                                                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(byte[] data)
                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(byte[] data,
                                                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(java.io.InputStream input)
                                                                                                                     throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(java.io.InputStream input,
                                                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                       throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseDelimitedFrom(java.io.InputStream input)
                                                                                                                              throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseDelimitedFrom(java.io.InputStream input,
                                                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                                                      throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(com.google.protobuf.CodedInputStream input,
                                                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                       throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code jraft.PBLogEntry}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
                                                                                                         implements
                                                                                                         // @@protoc_insertion_point(builder_implements:jraft.PBLogEntry)
                                                                                                         com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntryOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.class,
                        com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.Builder.class);
            }

            // Construct using com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.newBuilder()
            private Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                type_ = 0;
                term_ = 0L;
                index_ = 0L;
                peers_ = emptyList(com.google.protobuf.ByteString.class);
                oldPeers_ = emptyList(com.google.protobuf.ByteString.class);
                data_ = com.google.protobuf.ByteString.EMPTY;
                checksum_ = 0L;
                learners_ = emptyList(com.google.protobuf.ByteString.class);
                oldLearners_ = emptyList(com.google.protobuf.ByteString.class);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_descriptor;
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry getDefaultInstanceForType() {
                return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.getDefaultInstance();
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry build() {
                com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry buildPartial() {
                com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry result = new com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry(
                    this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.type_ = type_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.term_ = term_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.index_ = index_;
                    to_bitField0_ |= 0x00000004;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    peers_.makeImmutable();
                    result.peers_ = peers_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    oldPeers_.makeImmutable();
                    result.oldPeers_ = oldPeers_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.data_ = data_;
                    to_bitField0_ |= 0x00000008;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.checksum_ = checksum_;
                    to_bitField0_ |= 0x00000010;
                }
                if (((from_bitField0_ & 0x00000080) != 0)) {
                    learners_.makeImmutable();
                    result.learners_ = learners_;
                }
                if (((from_bitField0_ & 0x00000100) != 0)) {
                    oldLearners_.makeImmutable();
                    result.oldLearners_ = oldLearners_;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                            java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry) {
                    return mergeFrom((com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry other) {
                if (other == com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.getDefaultInstance())
                    return this;
                if (other.hasType()) {
                    setType(other.getType());
                }
                if (other.hasTerm()) {
                    setTerm(other.getTerm());
                }
                if (other.hasIndex()) {
                    setIndex(other.getIndex());
                }
                if (!other.peers_.isEmpty()) {
                    if (peers_.isEmpty()) {
                        peers_ = other.peers_;
                        peers_.makeImmutable();
                        bitField0_ |= 0x00000008;
                    } else {
                        ensurePeersIsMutable();
                        peers_.addAll(other.peers_);
                    }
                    onChanged();
                }
                if (!other.oldPeers_.isEmpty()) {
                    if (oldPeers_.isEmpty()) {
                        oldPeers_ = other.oldPeers_;
                        oldPeers_.makeImmutable();
                        bitField0_ |= 0x00000010;
                    } else {
                        ensureOldPeersIsMutable();
                        oldPeers_.addAll(other.oldPeers_);
                    }
                    onChanged();
                }
                if (other.hasData()) {
                    setData(other.getData());
                }
                if (other.hasChecksum()) {
                    setChecksum(other.getChecksum());
                }
                if (!other.learners_.isEmpty()) {
                    if (learners_.isEmpty()) {
                        learners_ = other.learners_;
                        learners_.makeImmutable();
                        bitField0_ |= 0x00000080;
                    } else {
                        ensureLearnersIsMutable();
                        learners_.addAll(other.learners_);
                    }
                    onChanged();
                }
                if (!other.oldLearners_.isEmpty()) {
                    if (oldLearners_.isEmpty()) {
                        oldLearners_ = other.oldLearners_;
                        oldLearners_.makeImmutable();
                        bitField0_ |= 0x00000100;
                    } else {
                        ensureOldLearnersIsMutable();
                        oldLearners_.addAll(other.oldLearners_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasType()) {
                    return false;
                }
                if (!hasTerm()) {
                    return false;
                }
                if (!hasIndex()) {
                    return false;
                }
                if (!hasData()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                 throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                int tmpRaw = input.readEnum();
                                com.alipay.sofa.jraft.entity.EnumOutter.EntryType tmpValue = com.alipay.sofa.jraft.entity.EnumOutter.EntryType
                                    .forNumber(tmpRaw);
                                if (tmpValue == null) {
                                    mergeUnknownVarintField(1, tmpRaw);
                                } else {
                                    type_ = tmpRaw;
                                    bitField0_ |= 0x00000001;
                                }
                                break;
                            } // case 8
                            case 16: {
                                term_ = input.readInt64();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 24: {
                                index_ = input.readInt64();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 24
                            case 34: {
                                com.google.protobuf.ByteString v = input.readBytes();
                                ensurePeersIsMutable();
                                peers_.add(v);
                                break;
                            } // case 34
                            case 42: {
                                com.google.protobuf.ByteString v = input.readBytes();
                                ensureOldPeersIsMutable();
                                oldPeers_.add(v);
                                break;
                            } // case 42
                            case 50: {
                                data_ = input.readBytes();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 50
                            case 56: {
                                checksum_ = input.readInt64();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 56
                            case 66: {
                                com.google.protobuf.ByteString v = input.readBytes();
                                ensureLearnersIsMutable();
                                learners_.add(v);
                                break;
                            } // case 66
                            case 74: {
                                com.google.protobuf.ByteString v = input.readBytes();
                                ensureOldLearnersIsMutable();
                                oldLearners_.add(v);
                                break;
                            } // case 74
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private int type_ = 0;

            /**
             * <code>required .jraft.EntryType type = 1;</code>
             * @return Whether the type field is set.
             */
            @java.lang.Override
            public boolean hasType() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required .jraft.EntryType type = 1;</code>
             * @return The type.
             */
            @java.lang.Override
            public com.alipay.sofa.jraft.entity.EnumOutter.EntryType getType() {
                com.alipay.sofa.jraft.entity.EnumOutter.EntryType result = com.alipay.sofa.jraft.entity.EnumOutter.EntryType
                    .forNumber(type_);
                return result == null ? com.alipay.sofa.jraft.entity.EnumOutter.EntryType.ENTRY_TYPE_UNKNOWN : result;
            }

            /**
             * <code>required .jraft.EntryType type = 1;</code>
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(com.alipay.sofa.jraft.entity.EnumOutter.EntryType value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>required .jraft.EntryType type = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = 0;
                onChanged();
                return this;
            }

            private long term_;

            /**
             * <code>required int64 term = 2;</code>
             * @return Whether the term field is set.
             */
            @java.lang.Override
            public boolean hasTerm() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>required int64 term = 2;</code>
             * @return The term.
             */
            @java.lang.Override
            public long getTerm() {
                return term_;
            }

            /**
             * <code>required int64 term = 2;</code>
             * @param value The term to set.
             * @return This builder for chaining.
             */
            public Builder setTerm(long value) {

                term_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 term = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearTerm() {
                bitField0_ = (bitField0_ & ~0x00000002);
                term_ = 0L;
                onChanged();
                return this;
            }

            private long index_;

            /**
             * <code>required int64 index = 3;</code>
             * @return Whether the index field is set.
             */
            @java.lang.Override
            public boolean hasIndex() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>required int64 index = 3;</code>
             * @return The index.
             */
            @java.lang.Override
            public long getIndex() {
                return index_;
            }

            /**
             * <code>required int64 index = 3;</code>
             * @param value The index to set.
             * @return This builder for chaining.
             */
            public Builder setIndex(long value) {

                index_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 index = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearIndex() {
                bitField0_ = (bitField0_ & ~0x00000004);
                index_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> peers_ = emptyList(com.google.protobuf.ByteString.class);

            private void ensurePeersIsMutable() {
                if (!peers_.isModifiable()) {
                    peers_ = makeMutableCopy(peers_);
                }
                bitField0_ |= 0x00000008;
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             * @return A list containing the peers.
             */
            public java.util.List<com.google.protobuf.ByteString> getPeersList() {
                peers_.makeImmutable();
                return peers_;
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             * @return The count of peers.
             */
            public int getPeersCount() {
                return peers_.size();
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             * @param index The index of the element to return.
             * @return The peers at the given index.
             */
            public com.google.protobuf.ByteString getPeers(int index) {
                return peers_.get(index);
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             * @param index The index to set the value at.
             * @param value The peers to set.
             * @return This builder for chaining.
             */
            public Builder setPeers(int index, com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePeersIsMutable();
                peers_.set(index, value);
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             * @param value The peers to add.
             * @return This builder for chaining.
             */
            public Builder addPeers(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePeersIsMutable();
                peers_.add(value);
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             * @param values The peers to add.
             * @return This builder for chaining.
             */
            public Builder addAllPeers(java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
                ensurePeersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, peers_);
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearPeers() {
                peers_ = emptyList(com.google.protobuf.ByteString.class);
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> oldPeers_ = emptyList(com.google.protobuf.ByteString.class);

            private void ensureOldPeersIsMutable() {
                if (!oldPeers_.isModifiable()) {
                    oldPeers_ = makeMutableCopy(oldPeers_);
                }
                bitField0_ |= 0x00000010;
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             * @return A list containing the oldPeers.
             */
            public java.util.List<com.google.protobuf.ByteString> getOldPeersList() {
                oldPeers_.makeImmutable();
                return oldPeers_;
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             * @return The count of oldPeers.
             */
            public int getOldPeersCount() {
                return oldPeers_.size();
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             * @param index The index of the element to return.
             * @return The oldPeers at the given index.
             */
            public com.google.protobuf.ByteString getOldPeers(int index) {
                return oldPeers_.get(index);
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             * @param index The index to set the value at.
             * @param value The oldPeers to set.
             * @return This builder for chaining.
             */
            public Builder setOldPeers(int index, com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOldPeersIsMutable();
                oldPeers_.set(index, value);
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             * @param value The oldPeers to add.
             * @return This builder for chaining.
             */
            public Builder addOldPeers(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOldPeersIsMutable();
                oldPeers_.add(value);
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             * @param values The oldPeers to add.
             * @return This builder for chaining.
             */
            public Builder addAllOldPeers(java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
                ensureOldPeersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, oldPeers_);
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearOldPeers() {
                oldPeers_ = emptyList(com.google.protobuf.ByteString.class);
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes data = 6;</code>
             * @return Whether the data field is set.
             */
            @java.lang.Override
            public boolean hasData() {
                return ((bitField0_ & 0x00000020) != 0);
            }

            /**
             * <code>required bytes data = 6;</code>
             * @return The data.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <code>required bytes data = 6;</code>
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                data_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes data = 6;</code>
             * @return This builder for chaining.
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000020);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            private long checksum_;

            /**
             * <code>optional int64 checksum = 7;</code>
             * @return Whether the checksum field is set.
             */
            @java.lang.Override
            public boolean hasChecksum() {
                return ((bitField0_ & 0x00000040) != 0);
            }

            /**
             * <code>optional int64 checksum = 7;</code>
             * @return The checksum.
             */
            @java.lang.Override
            public long getChecksum() {
                return checksum_;
            }

            /**
             * <code>optional int64 checksum = 7;</code>
             * @param value The checksum to set.
             * @return This builder for chaining.
             */
            public Builder setChecksum(long value) {

                checksum_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 checksum = 7;</code>
             * @return This builder for chaining.
             */
            public Builder clearChecksum() {
                bitField0_ = (bitField0_ & ~0x00000040);
                checksum_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> learners_ = emptyList(com.google.protobuf.ByteString.class);

            private void ensureLearnersIsMutable() {
                if (!learners_.isModifiable()) {
                    learners_ = makeMutableCopy(learners_);
                }
                bitField0_ |= 0x00000080;
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             * @return A list containing the learners.
             */
            public java.util.List<com.google.protobuf.ByteString> getLearnersList() {
                learners_.makeImmutable();
                return learners_;
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             * @return The count of learners.
             */
            public int getLearnersCount() {
                return learners_.size();
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             * @param index The index of the element to return.
             * @return The learners at the given index.
             */
            public com.google.protobuf.ByteString getLearners(int index) {
                return learners_.get(index);
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             * @param index The index to set the value at.
             * @param value The learners to set.
             * @return This builder for chaining.
             */
            public Builder setLearners(int index, com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLearnersIsMutable();
                learners_.set(index, value);
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             * @param value The learners to add.
             * @return This builder for chaining.
             */
            public Builder addLearners(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLearnersIsMutable();
                learners_.add(value);
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             * @param values The learners to add.
             * @return This builder for chaining.
             */
            public Builder addAllLearners(java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
                ensureLearnersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, learners_);
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             * @return This builder for chaining.
             */
            public Builder clearLearners() {
                learners_ = emptyList(com.google.protobuf.ByteString.class);
                bitField0_ = (bitField0_ & ~0x00000080);
                onChanged();
                return this;
            }

            private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> oldLearners_ = emptyList(com.google.protobuf.ByteString.class);

            private void ensureOldLearnersIsMutable() {
                if (!oldLearners_.isModifiable()) {
                    oldLearners_ = makeMutableCopy(oldLearners_);
                }
                bitField0_ |= 0x00000100;
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             * @return A list containing the oldLearners.
             */
            public java.util.List<com.google.protobuf.ByteString> getOldLearnersList() {
                oldLearners_.makeImmutable();
                return oldLearners_;
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             * @return The count of oldLearners.
             */
            public int getOldLearnersCount() {
                return oldLearners_.size();
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             * @param index The index of the element to return.
             * @return The oldLearners at the given index.
             */
            public com.google.protobuf.ByteString getOldLearners(int index) {
                return oldLearners_.get(index);
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             * @param index The index to set the value at.
             * @param value The oldLearners to set.
             * @return This builder for chaining.
             */
            public Builder setOldLearners(int index, com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOldLearnersIsMutable();
                oldLearners_.set(index, value);
                bitField0_ |= 0x00000100;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             * @param value The oldLearners to add.
             * @return This builder for chaining.
             */
            public Builder addOldLearners(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOldLearnersIsMutable();
                oldLearners_.add(value);
                bitField0_ |= 0x00000100;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             * @param values The oldLearners to add.
             * @return This builder for chaining.
             */
            public Builder addAllOldLearners(java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
                ensureOldLearnersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, oldLearners_);
                bitField0_ |= 0x00000100;
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             * @return This builder for chaining.
             */
            public Builder clearOldLearners() {
                oldLearners_ = emptyList(com.google.protobuf.ByteString.class);
                bitField0_ = (bitField0_ & ~0x00000100);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:jraft.PBLogEntry)
        }

        // @@protoc_insertion_point(class_scope:jraft.PBLogEntry)
        private static final com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry();
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<PBLogEntry> PARSER = new com.google.protobuf.AbstractParser<PBLogEntry>() {
                                                                              @java.lang.Override
                                                                              public PBLogEntry parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                             throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                  Builder builder = newBuilder();
                                                                                  try {
                                                                                      builder.mergeFrom(input,
                                                                                          extensionRegistry);
                                                                                  } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                                                                                      throw e
                                                                                          .setUnfinishedMessage(builder
                                                                                              .buildPartial());
                                                                                  } catch (com.google.protobuf.UninitializedMessageException e) {
                                                                                      throw e
                                                                                          .asInvalidProtocolBufferException()
                                                                                          .setUnfinishedMessage(
                                                                                              builder.buildPartial());
                                                                                  } catch (java.io.IOException e) {
                                                                                      throw new com.google.protobuf.InvalidProtocolBufferException(
                                                                                          e)
                                                                                          .setUnfinishedMessage(builder
                                                                                              .buildPartial());
                                                                                  }
                                                                                  return builder.buildPartial();
                                                                              }
                                                                          };

        public static com.google.protobuf.Parser<PBLogEntry> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PBLogEntry> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_jraft_PBLogEntry_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_jraft_PBLogEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\tlog.proto\022\005jraft\032\nenum.proto\"\263\001\n\nPBLog"
                                              + "Entry\022\036\n\004type\030\001 \002(\0162\020.jraft.EntryType\022\014\n"
                                              + "\004term\030\002 \002(\003\022\r\n\005index\030\003 \002(\003\022\r\n\005peers\030\004 \003("
                                              + "\014\022\021\n\told_peers\030\005 \003(\014\022\014\n\004data\030\006 \002(\014\022\020\n\010ch"
                                              + "ecksum\030\007 \001(\003\022\020\n\010learners\030\010 \003(\014\022\024\n\014old_le"
                                              + "arners\030\t \003(\014B2\n%com.alipay.sofa.jraft.en"
                                              + "tity.codec.v2B\tLogOutter" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] { com.alipay.sofa.jraft.entity.EnumOutter
                .getDescriptor(), });
        internal_static_jraft_PBLogEntry_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_jraft_PBLogEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_jraft_PBLogEntry_descriptor, new java.lang.String[] { "Type", "Term", "Index", "Peers",
            "OldPeers", "Data", "Checksum", "Learners", "OldLearners", });
        com.alipay.sofa.jraft.entity.EnumOutter.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
